select
  gpu_family_id,
  price_level_usd_gpu_hr,
  configuration_count,
  provider_count,
  single_gpu_configuration_count,
  minimum_offer_usd_gpu_hr,
  maximum_offer_usd_gpu_hr,
  entered_count,
  repriced_count,
  left_availability_count,
  stock_status_changed_count,
  remained_count,
  reference_usd_gpu_hr,
  market_benchmark_usd_gpu_hr,
  distance_from_prime_reference_usd_gpu_hr,
  distance_from_market_benchmark_usd_gpu_hr,
  premium_to_market_benchmark_fraction,
  is_prime_reference_level,
  is_market_benchmark_level,
  status,
  gold_observed_at,
  gold_run_id,
  methodology_version
from fact_prime_frontier_offer_ladder
order by gpu_family_id, price_level_usd_gpu_hr desc
